'use strict';
const $=id=>document.getElementById(id);let data,entries=[],selected=null;
function text(html){const d=new DOMParser().parseFromString(String(html??''),'text/html');return d.body.textContent||'';}
function el(tag,value,cls){const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n;}
function card(title,body){const c=el('section',undefined,'card');c.append(el('h3',title),el('p',body));return c;}
function list(){const q=$('search').value.trim().toLocaleLowerCase('de'),f=$('filter').value;const a=entries.filter(e=>(f==='all'||e.track===f)&&(e.title+' '+e.trackName+' '+e.id).toLocaleLowerCase('de').includes(q));$('count').textContent=a.length+' Treffer';$('catalog').replaceChildren(...a.map(e=>{const b=el('button',e.title);b.type='button';b.classList.toggle('active',selected===e.id);b.onclick=()=>show(e);return b}));}
function appendStates(target,e){const g=el('div',undefined,'grid');const rows=e.recipe?['Eigener Testprozess, Bash 4+, Linux-Werkzeuge','Vorgegebenes Beispiel ausführen','stdout und Exit-Status gegen Erwartung prüfen','Testprozess beenden; Prüflog bleibt erhalten']:['Originallektion und Voraussetzungen lesen','Die in der Quelle beschriebene Aufgabe untersuchen','Eigenes Ergebnis mit den angegebenen Kriterien vergleichen','Zum Original und erhaltenen Arbeitsstand zurückkehren'];rows.forEach((s,i)=>g.append(card(['T⁻ · Voraussetzung','T⁰ · Handlung','T⁺ · Ergebnis','T↩ · Rückweg'][i],s)));target.append(g);}
function show(e){selected=e.id;const d=$('detail');d.replaceChildren(el('h2',e.title));d.append(el('span',e.recipe?'BASH · CLOUDTEST':'ORIGINAL + THEMENBRÜCKE','badge'));const t=el('span',e.trackName,'badge');d.append(t);
if(e.recipe){d.append(card('Kanonische Handlung',e.recipe.explanation));const c=el('section',undefined,'card');c.append(el('h3','Bash · tatsächlich prüfbares Beispiel'),el('pre',e.recipe.bash));const copy=el('button','Bash-Beispiel kopieren');copy.onclick=async()=>{try{await navigator.clipboard.writeText(e.recipe.bash);copy.textContent='Kopiert'}catch{copy.textContent='Bitte Code manuell markieren'}};c.append(copy,el('h3','Erwartete Ausgabe'),el('pre',e.recipe.expected));const a=el('a','Cloud-Prüfläufe öffnen');a.href='https://github.com/Juri-Halveth/mein-lernportal/actions/workflows/big-bang.yml';c.append(a);d.append(c);}else{
const origin=el('section',undefined,'card');origin.append(el('h3','Vollständiger Originalinhalt · Textansicht'));const beats=e.lesson.beats||[];for(const b of beats){if(b.html)origin.append(el('p',text(b.html)));if(b.frage)origin.append(el('p',text(b.frage)));if(b.code)origin.append(el('pre',String(b.code)));if(Array.isArray(b.optionen))b.optionen.forEach((o,i)=>origin.append(el('p',(i+1)+'. '+text(o))));if(b.enthuellung){const more=el('details');more.append(el('summary','Erklärung anzeigen'),el('p',text(b.enthuellung)));origin.append(more);}}
if(e.lesson.task){origin.append(el('h3','Originalaufgabe'),el('pre',JSON.stringify(e.lesson.task,(k,v)=>typeof v==='function'?'[Prüffunktion im Originalportal]':v,2)));}
if(e.lesson.questions)origin.append(el('pre',JSON.stringify(e.lesson.questions,null,2)));
const a=el('a','Originallektion mit Übungen und Visualisierungen öffnen');a.href='../#lesson/'+encodeURIComponent(e.id);origin.append(a);d.append(origin);
const bridge=data.bridges[e.track]||['Offene Brücke','Für diese Themenwelt ist noch keine gebundene Bash-Entsprechung vorhanden.','printf'];d.append(card('Bash-Themenbrücke · '+bridge[0],bridge[1]));const r=data.recipes.find(r=>r.concept===bridge[2]);if(r){const b=el('button','Verwandtes Bash-Labor: '+r.title);b.onclick=()=>show(entries.find(e=>e.id===r.id));d.append(b);}}
appendStates(d,e);const lenses=el('div',undefined,'grid');const purpose=e.recipe?e.recipe.explanation:e.title;[['Bash / systemisch','Benannte Prozesse, Eingaben, Ausgaben und Exit-Status.'],['Technisch','Laufzeit, Repräsentation und Schnittstellen der konkreten Aufgabe binden.'],['Mathematisch','Zustandsraum und Operator zuerst definieren. Thema: '+purpose],['Physikalisch','Die Website zeigt Softwarezustände; eine physische Messung braucht einen eigenen Beobachter.'],['Philosophisch','Handlung, Absicht und Interpretation als getrennte Perspektiven betrachten.'],['Juristisch','Rolle, Erlaubnis und Wirkung sind eigene Fragen. Ein Lernbeispiel erteilt keine fremde Zugriffsbefugnis.'],['Linguistisch','Ähnliche Wörter benötigen keine identische Definition.'],['Biologisch','Biologische Analogien erhalten einen eigenen Modellstatus. Hier wird kein Organismus gemessen.'],['Menschlich','Ich verstehe den Schritt, prüfe mein Ergebnis und finde den Rückweg.']].forEach(([k,v])=>lenses.append(card(k,v)));d.append(el('h2','Neun Perspektiven'),lenses,card('Gegenmodell und Claim-Grenze','Eine Themenbrücke ist keine automatische Übersetzung der vollständigen Lektion. Bash orchestriert viele Aufgaben, ersetzt aber weder Browser-Rendering, ML-Training noch menschliche Zustimmung. Die Originallektion behält ihre Bedeutung.'));list();history.replaceState(null,'','#'+encodeURIComponent(e.id));}
async function boot(){try{const response=await fetch('catalog.json',{cache:'no-cache'});if(!response.ok)throw Error('Katalog HTTP '+response.status);data=await response.json();const c=window.CURRICULUM;if(!c||!Array.isArray(c.tracks))throw Error('Curriculum fehlt');entries=data.recipes.map(r=>({id:r.id,title:r.title,track:'bash',trackName:'Bash-Labor',recipe:r}));for(const t of c.tracks){if(![...$('filter').options].some(o=>o.value===t.id)){const o=el('option',t.name);o.value=t.id;$('filter').append(o);}for(const s of t.stages)for(const l of s.lessons)entries.push({id:l.id,title:l.title,track:t.id,trackName:t.name,stage:s,lesson:l});}const originalCount=entries.filter(e=>!e.recipe).length;$('stats').textContent=originalCount+' Originallektionen · '+data.recipes.length+' Bash-Labore · '+c.tracks.length+' Themenwelten · aus dem GitHub-Curriculum';$('search').oninput=list;$('filter').onchange=list;$('refresh').onclick=()=>location.reload();$('sources').replaceChildren(el('h3','Weiterlernen · offizielle Dokumentation und Lernplattformen'),...data.sources.map(([n,u])=>{const p=el('p');const a=el('a',n);a.href=u;a.rel='noopener';p.append(a);return p}));list();const id=decodeURIComponent(location.hash.slice(1));show(entries.find(e=>e.id===id)||entries[0]);}catch(error){$('stats').textContent='Laden fehlgeschlagen: '+error.message;}}
boot();